# Generated by Django 3.2.4 on 2021-07-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_added_characteristics_to_users_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email')},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
